### PR TITLE
VIDCS-96 - Captions API Improvements

### PR DESCRIPTION
**Pull request by behei-vonage**
This PR makes some changes that should make captions be more consistent with archiving and make the client's life easier (hopefully).

### CODE REVIEW

**Review by conshus — APPROVED** [review]
Looks good to me! Thanks!!

**Comment by manchuck** [comment]
If a caption is never stopped, is that an issue? Also, is there a limit to the number of captions that can be started for a session?

**Comment by behei-vonage** [comment]
> If a caption is never stopped, is that an issue? Also, is there a limit to the number of captions that can be started for a session?

@manchuck, if the captions are never stopped, it'll be stopped by our servers after a certain amount of time. Also, there is currently only one captionsId allowed per session

**Comment by manchuck** [comment]
> there is currently only one captionsId allowed per session

With that said, If I start captions, then refresh the browser (thus losing the captions id) and call the API to start captioning again, do I get the same id?

**Review by manchuck — APPROVED** [review]

**Pull request merged**
